[book]
authors = ["许杰友 Jieyou Xu (Joe)"]
language = "en"
multilingual = false
src = "src"
title = "Joe's Random Thoughts"

[rust]
edition = "2018"

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/jieyouxu/jieyouxu.github.io"

